# Generated by Django 4.0.4 on 2022-05-27 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tetris', '0004_alter_profile_line_alter_profile_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='line',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='score',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
